# AR预测视频模型配置文件

# 数据配置
data:
  data_root: "/sharefiles4/qubohuan/"  # 数据根路径
  time_interval: 6  # 时间间隔（小时），6表示每6小时一个样本，1表示每小时一个样本
  
  # 使用的变量配置（最少9个变量）
  variables:
    # 单层变量（4个）
    single_level:
      - "t2m_npy"    # 2米温度
      - "tp_npy"     # 总降水量
      - "u10_npy"    # 10米u风分量
      - "v10_npy"    # 10米v风分量
    
    # 多层变量（13层每个）- 指定使用的层级
    multi_level:
      - variable: "r_npy"     # 相对湿度
        levels: ["level_00"]  # 使用的层级
      - variable: "t_npy"     # 温度
        levels: ["level_00"]  # 使用的层级
      - variable: "u_npy"     # u风分量
        levels: ["level_00"]  # 使用的层级
      - variable: "v_npy"     # v风分量
        levels: ["level_00"]  # 使用的层级  
      - variable: "z_npy"     # 位势高度
        levels: ["level_00"]  # 使用的层级
  
  # 数据集划分
  years:
    train: [1979, 2013]      # 训练集年份范围
    test: [2014, 2014]       # 测试集年份
    val: [2015, 2015]        # 验证集年份
  
  # 数据加载参数
  batch_size: 16
  shuffle: true              # 是否随机打乱
  num_workers: 4

# 模型配置
model:
  name: "ar_pred_video_vanilla"
  
  # 时间窗口配置
  time_window: 8             # 时间窗口大小t
  
  # Patch嵌入配置
  patch_size: [16, 16]       # patch大小 [height, width]
  embed_dim: 768             # 嵌入维度
  
  # 时空区块划分
  block_division: "temporal" # 区块划分规则: "temporal", "spatial", "random"
  
  # Random patchify配置
  random_patchify: true      # 是否使用随机patchify
  
  # Transformer配置
  encoder:
    num_layers: 8            # Encoder层数m
    num_heads: 12            # 多头注意力头数h
    mlp_ratio: 4.0           # MLP隐藏层比例
    dropout: 0.1             # Dropout率
    
  decoder:
    num_layers: 4            # Decoder层数
    hidden_dim: 512          # Decoder隐藏维度
    num_heads: 8             # Decoder注意力头数
    dropout: 0.1             # Dropout率
  
  # 掩码配置
  mask_ratio: 0.8            # 自回归掩码率
  
  # 激活函数和归一化
  activation: "gelu"         # 激活函数
  norm_layer: "layernorm"    # 归一化层

# 训练配置
training:
  num_epochs: 100
  learning_rate: 1e-4
  optimizer: "adam"
  weight_decay: 1e-5
  
  # 学习率调度
  lr_scheduler:
    type: "cosine"           # 学习率调度器类型
    warmup_epochs: 10        # 预热轮数
  
  # 损失函数
  loss_function: "mse"       # 损失函数类型
  
  # 检查点保存
  save_every: 10             # 每多少轮保存一次检查点
  save_best: true            # 是否保存最佳模型
  
  # 早停
  early_stopping:
    patience: 20             # 早停耐心值
    min_delta: 1e-6          # 最小改善幅度

# 验证和测试配置
evaluation:
  eval_every: 5              # 每多少轮评估一次
  visualize_samples: 4       # 可视化样本数量

# 日志和监控配置
logging:
  log_level: "INFO"
  wandb:
    project: "ar_pred_video"
    entity: null             # Wandb实体名称，如果为null则使用默认
    name: null               # 实验名称，如果为null则自动生成
    tags: ["ar_prediction", "video", "vanilla"]

# 系统配置
system:
  seed: 42                   # 随机种子
  device: "cuda"             # 设备类型
  mixed_precision: true      # 是否使用混合精度训练